### ISSUE TITLE
Custom allocators don't support user-provided state

### ISSUE THREAD

**Issue by rkevingibson** [nicebyte/nicegraf#205]
I appreciate the ability to provide `ngf_allocation_callbacks`, but one problem is that the callbacks don't take a `void* userdata` parameter, requiring any custom allocators to rely on global state. I'm happy to do the changes and submit a PR but wanted to see if there's interest first. It seems like a fairly small change, since all allocations seem to go through macros `NGFI_ALLOC/NGFI_FREE`, so the change would be:
- Adding a `void* userdata` field to `ngf_allocation_callbacks`
- Changing the signatures of `allocate` and `free` in `ngf_allocation_callbacks` to take a `void*` as a final argument.
- Changing the `NGFI_ALLOC/FREE` macros to pass in the userdata pointer.

**Comment by nicebyte** [comment]
Sure, that would be a nice improvement. Feel free to submit a PR. Thank you!
