### ISSUE TITLE
crash after binding another gfx pipeline without re-binding buffers after

### ISSUE THREAD

**Issue by dBagrat** [nicebyte/nicegraf#47]
steps to reproduce:
in: https://github.com/nicebyte/nicegraf-samples/blob/master/vol-01/03-hexagon/hexagon.cpp

Create a duplicate pipeline
```cpp
state->pipeline_test.initialize(pipe_info);
```
and switch to it after binding vert_buffer:
```cpp
  ngf_cmd_bind_gfx_pipeline(renc, state->pipeline);
  ngf_cmd_bind_attrib_buffer(renc, state->vert_buffer, 0u, 0u);
  ngf_cmd_bind_gfx_pipeline(renc, state->pipeline_test);
```

**Comment by nicebyte** [comment]
fixed by d86941a5bebba9c641560acbe49eb701829b8516 & 96ef582caa755821dbcf11db896cd12760791d7a
